In [1]:
import pandas as pd
df = pd.read_csv('../../Datasets/spotify_history.csv')
df.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False

In [2]:
df.shape

(149860, 11)

In [3]:
df.isnull().sum()

spotify_track_uri      0
ts                     0
platform               0
ms_played              0
track_name             0
artist_name            0
album_name             0
reason_start         143
reason_end           117
shuffle                0
skipped                0
dtype: int64

In [4]:
# Handling Missing Data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
df['reason_end'] = imputer.fit_transform(df[['reason_end']]).ravel()
df['reason_start'] = imputer.fit_transform(df[['reason_start']]).ravel()

In [5]:
df.isnull().sum()

spotify_track_uri    0
ts                   0
platform             0
ms_played            0
track_name           0
artist_name          0
album_name           0
reason_start         0
reason_end           0
shuffle              0
skipped              0
dtype: int64

In [6]:
df['platform'].unique()

array(['web player', 'windows', 'android', 'iOS', 'cast to device', 'mac'],
      dtype=object)

In [7]:
# Feature Scaling 
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
df['scaled_ms_played']= mms.fit_transform(df[['ms_played']]).ravel()

In [8]:
# Encoding Categorical Data 
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
df['platform_encoded'] = le.fit_transform(df['platform']).ravel()
df['reason_start_encoded'] = le.fit_transform(df['reason_start']).ravel()
df['reason_end_encoded'] = le.fit_transform(df['reason_end']).ravel()
df['shuffle_encoded'] = le.fit_transform(df['shuffle']).ravel()
df['skipped_encoded'] = le.fit_transform(df['skipped']).ravel()

In [9]:
df

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,scaled_ms_played,platform_encoded,reason_start_encoded,reason_end_encoded,shuffle_encoded,skipped_encoded
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False,0.002040,4,1,2,0,0
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,0.039628,4,3,2,0,0
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False,0.182808,4,3,14,0,0
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False,0.085850,4,10,2,0,0
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False,0.000000,4,3,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149855,4Fz1WWr5o0OrlIcZxcyZtK,2024-12-15 23:06:19,android,1247,On The Way Home,John Mayer,Paradise Valley,fwdbtn,fwdbtn,True,True,0.000799,0,5,4,1,1
149856,0qHMhBZqYb99yhX9BHcIkV,2024-12-15 23:06:21,android,1515,Magical Mystery Tour - Remastered 2009,The Beatles,Magical Mystery Tour,fwdbtn,fwdbtn,True,True,0.000970,0,5,4,1,1
149857,0HHdujGjOZChTrl8lJWEIq,2024-12-15 23:06:22,android,1283,"Stop This Train - Live at the Nokia Theatre, L...",John Mayer,Where the Light Is: John Mayer Live In Los Ang...,fwdbtn,fwdbtn,True,True,0.000822,0,5,4,1,1
149858,7peh6LUcdNPcMdrSH4JPsM,2024-12-15 23:06:23,android,1306,I Don't Trust Myself (With Loving You),John Mayer,Continuum,fwdbtn,fwdbtn,True,True,0.000837,0,5,4,1,1
149859,6iGU74CwXuT4XVepjc9Emf,2024-12-15 23:06:25,android,1893,God Only Knows - Mono,The Beach Boys,Pet Sounds,fwdbtn,fwdbtn,True,True,0.001213,0,5,4,1,1

In [13]:
# Dropping unnecessary columns 
df = df.drop(columns = ['spotify_track_uri','ts' , 'track_name' , 'artist_name' , 'album_name'])

In [14]:
df

,platform,ms_played,reason_start,reason_end,shuffle,skipped,scaled_ms_played,platform_encoded,reason_start_encoded,reason_end_encoded,shuffle_encoded,skipped_encoded
0,web player,3185,autoplay,clickrow,False,False,0.002040,4,1,2,0,0
1,web player,61865,clickrow,clickrow,False,False,0.039628,4,3,2,0,0
2,web player,285386,clickrow,unknown,False,False,0.182808,4,3,14,0,0
3,web player,134022,trackdone,clickrow,False,False,0.085850,4,10,2,0,0
4,web player,0,clickrow,nextbtn,False,False,0.000000,4,3,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
149855,android,1247,fwdbtn,fwdbtn,True,True,0.000799,0,5,4,1,1
149856,android,1515,fwdbtn,fwdbtn,True,True,0.000970,0,5,4,1,1
149857,android,1283,fwdbtn,fwdbtn,True,True,0.000822,0,5,4,1,1
149858,android,1306,fwdbtn,fwdbtn,True,True,0.000837,0,5,4,1,1
149859,android,1893,fwdbtn,fwdbtn,True,True,0.001213,0,5,4,1,1

In [15]:
# Separate Features and Target 
X = df.drop(columns = ['ms_played'])
y = df['ms_played']

In [16]:
# Splitting Data into Training and the Test sets 
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size=0.2 , random_state= 1)

In [19]:
print(X)

          platform reason_start reason_end  shuffle  skipped  \
0       web player     autoplay   clickrow    False    False
1       web player     clickrow   clickrow    False    False
2       web player     clickrow    unknown    False    False
3       web player    trackdone   clickrow    False    False
4       web player     clickrow    nextbtn    False    False
...            ...          ...        ...      ...      ...
149855     android       fwdbtn     fwdbtn     True     True
149856     android       fwdbtn     fwdbtn     True     True
149857     android       fwdbtn     fwdbtn     True     True
149858     android       fwdbtn     fwdbtn     True     True
149859     android       fwdbtn     fwdbtn     True     True

        scaled_ms_played  platform_encoded  reason_start_encoded  \
0               0.002040                 4                     1
1               0.039628                 4                     3
2               0.182808                 4                     3
3               0.085850                 4                    10
4               0.000000                 4                     3
...                  ...               ...                   ...
149855          0.000799                 0                     5
149856          0.000970                 0                     5
149857          0.000822                 0                     5
149858          0.000837                 0                     5
149859          0.001213                 0                     5

        reason_end_encoded  shuffle_encoded  skipped_encoded
0                        2                0                0
1                        2                0                0
2                       14                0                0
3                        2                0                0
4                        6                0                0
...                    ...              ...              ...
149855                   4                1                1
149856                   4                1                1
149857                   4                1                1
149858                   4                1                1
149859                   4                1                1

[149860 rows x 11 columns]

In [18]:
print(y)

0           3185
1          61865
2         285386
3         134022
4              0
           ...
149855      1247
149856      1515
149857      1283
149858      1306
149859      1893
Name: ms_played, Length: 149860, dtype: int64